### ISSUE TITLE
Error on startup 

### ISSUE THREAD

**Issue by cyberralf83** [themoosman/weewx-ambientweatherapi-json#1]
Hey, 
Thank you so much for making this driver. It could be useful to a lot of people. I am getting an error when starting it up. I've installed it through "pip install ambient_api" and then added the two .py files to /usr/share/weewx/user and also edited the /etc/weewx/weewx.conf file with the api key and user.ambientweatherapi.
Thanks again.

Here is the log. 
May 25 01:26:05 PiBridge systemd[1]: Starting LSB: weewx weather system...
May 25 01:26:05 PiBridge weewx[5467] INFO __main__: Initializing weewx version 4.0.0
May 25 01:26:05 PiBridge weewx[5467] INFO __main__: Using Python 3.7.3 (default, Dec 20 2019, 18:57:59) #012[GCC 8.3.0]
May 25 01:26:05 PiBridge weewx[5467] INFO __main__: Platform Linux-4.19.97-v7l+-armv7l-with-debian-10.4
May 25 01:26:05 PiBridge weewx[5467] INFO __main__: Locale is 'en_US.UTF-8'
May 25 01:26:05 PiBridge weewx[5467] INFO __main__: PID file is /var/run/weewx.pid
May 25 01:26:05 PiBridge weewx[5471] INFO __main__: Using configuration file /etc/weewx/weewx.conf
May 25 01:26:05 PiBridge weewx[5471] INFO weewx.engine: Loading station type ambientweatherapi (user.ambientweatherapi)
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__: Caught unrecoverable exception:
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****  invalid syntax (ambientweatherapi.py, line 266)
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****  Traceback (most recent call last):
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 148, in main
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 69, in __init__
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****      self.setupStation(config_dict)
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 92, in setupStation
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****      __import__(driver)
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****    File "/usr/share/weewx/user/ambientweatherapi.py", line 266
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****      print weeutil.weeutil.timestamp_to_string(packet['dateTime']), packet
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****                  ^
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****  SyntaxError: invalid syntax
May 25 01:26:05 PiBridge weewx[5471] CRITICAL __main__:     ****  Exiting.

Thanks again.

**Comment by themoosman** [comment]
Huh, so I wasn't aware that Weewx 4.0 with Python3 support got released.  Let me upgrade my instance and submit a fix for this issue.
