### ISSUE TITLE
Throwing error it can't find ambientweather-api

### ISSUE THREAD

**Issue by staze** [themoosman/weewx-ambientweatherapi-json#15]
Got this all installed. pip says everything is good. Trying to fire it up after configuring weewx, I get:

Aug  4 15:38:25 raspi-server-misc weewx[5860] INFO weewx.engine: Loading station type ambientweatherapi (user.ambientweatherapi)
Aug  4 15:38:25 raspi-server-misc weewx[5860] CRITICAL __main__:     ****  No module named ambient_api.ambientapi
Aug  4 15:38:25 raspi-server-misc weewx[5860] CRITICAL __main__:     ****    File "/usr/share/weewx/user/ambientweatherapi.py", line 9, in <module>
Aug  4 15:38:25 raspi-server-misc weewx[5860] CRITICAL __main__:     ****      from ambient_api.ambientapi import AmbientAPI
Aug  4 15:38:25 raspi-server-misc weewx[5860] CRITICAL __main__:     ****  ImportError: No module named ambient_api.ambientapi

Yet:

sudo -H pip3 install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: ambient-api>=1.5.5 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (1.5.5)
Requirement already satisfied: flake8>=3.8.3 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 2)) (3.8.3)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from ambient-api>=1.5.5->-r requirements.txt (line 1)) (2.21.0)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from ambient-api>=1.5.5->-r requirements.txt (line 1)) (1.24.1)
Requirement already satisfied: pycodestyle<2.7.0,>=2.6.0a1 in /usr/local/lib/python3.7/dist-packages (from flake8>=3.8.3->-r requirements.txt (line 2)) (2.6.0)
Requirement already satisfied: pyflakes<2.3.0,>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from flake8>=3.8.3->-r requirements.txt (line 2)) (2.2.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from flake8>=3.8.3->-r requirements.txt (line 2)) (1.7.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from flake8>=3.8.3->-r requirements.txt (line 2)) (0.6.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata; python_version < "3.8"->flake8>=3.8.3->-r requirements.txt (line 2)) (3.1.0)

This is on a Raspi running Ubuntu Buster.

**Comment by staze** [comment]
oooh... weewx is running under Python2....

**Comment by themoosman** [comment]
```
This driver uses the AmbientAPI Python3 pakcage to make the API calls.

This driver only works with Weewx 4.0+ and Python3.
```

**Comment by staze** [comment]
Yup. I had installed weewx for python2. reinstalled python3 version, fired it up, and it's working. 

Thanks!
