### ISSUE TITLE
Works perfect under Centos 8, errors under Centos 7

### ISSUE THREAD

**Issue by pipporobby** [themoosman/weewx-ambientweatherapi-json#16]
Wonderful job you did! No problem with Centos 8 https://benpag.com/

With Centos 7 (or Ubuntu 18) I get these errors:

Sep  5 01:42:13 localhost /weewxd: Error caught was: AmbientAPI get_devices() returned empty dict
Sep  5 01:42:13 localhost journal: weewx[15721] ERROR root: Error caught was: AmbientAPI get_devices() returned empty dict
Sep  5 01:42:13 localhost /weewxd: ambientweatherapi driver had an error sending data to weewx.
Sep  5 01:42:13 localhost journal: weewx[15721] ERROR root: ambientweatherapi driver had an error sending data to weewx.
Sep  5 01:42:13 localhost /weewxd: Error caught was: Previous error occured, skipping packet build.

**Comment by themoosman** [comment]
What version of Python?  Can you increase the log level to debug and attach a log?

**Comment by pipporobby** [comment]
I elevated to log level 2. Hope this can help. Thanks

Sep  5 21:53:38 localhost journal: weewx[9788] INFO __main__: Initializing weewx version 4.1.1
Sep  5 21:53:38 localhost journal: weewx[9788] INFO __main__: Using Python 3.6.8 (default, Apr  2 2020, 13:34:55) #012[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Sep  5 21:53:38 localhost journal: weewx[9788] INFO __main__: Platform Linux-3.10.0-1127.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Sep  5 21:53:38 localhost journal: weewx[9788] INFO __main__: Locale is 'en_US.UTF-8'
Sep  5 21:53:38 localhost journal: weewx[9788] INFO __main__: Using configuration file /home/weewx/weewx.conf
Sep  5 21:53:38 localhost journal: weewx[9788] INFO __main__: Debug is 0
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.engine: Loading station type ambientweatherapi (user.ambientweatherapi)
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.engine: StdConvert target unit is 0x1
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.wxservices: The following values will be calculated: pressure=prefer_hardware, altimeter=prefer_hardware, appTemp=prefer_hardware, barometer=prefer_hardware, beaufort=prefer_hardware, cloudbase=prefer_hardware, dewpoint=prefer_hardware, ET=prefer_hardware, heatindex=prefer_hardware, humidex=prefer_hardware, inDewpoint=prefer_hardware, maxSolarRad=prefer_hardware, rainRate=prefer_hardware, windchill=prefer_hardware, windrun=prefer_hardware
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.wxservices: The following algorithms will be used for calculations: altimeter=aaASOS, maxSolarRad=RS
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.engine: Archive will use data binding wx_binding
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.engine: Record generation will be attempted in 'hardware'
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.engine: Using archive interval of 60 seconds (specified in weewx configuration)
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.restx: StationRegistry: Registration not requested.
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.restx: Wunderground: Posting not enabled.
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.restx: PWSweather: Posting not enabled.
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.restx: CWOP: Posting not enabled.
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.restx: WOW: Posting not enabled.
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.restx: AWEKAS: Posting not enabled.
Sep  5 21:53:38 localhost journal: weewx[9788] INFO __main__: Starting up weewx version 4.1.1
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.manager: Starting backfill of daily summaries
Sep  5 21:53:38 localhost journal: weewx[9788] INFO weewx.engine: Starting main packet loop.
Sep  5 21:53:42 localhost journal: weewx[9788] ERROR root: AmbientAPI get_devices() returned empty dict
Sep  5 21:53:42 localhost /weewxd: ambientweatherapi driver encountered an error.
Sep  5 21:53:42 localhost journal: weewx[9788] ERROR root: ambientweatherapi driver encountered an error.
Sep  5 21:53:42 localhost /weewxd: Error caught was: AmbientAPI get_devices() returned empty dict
Sep  5 21:53:42 localhost journal: weewx[9788] ERROR root: Error caught was: AmbientAPI get_devices() returned empty dict
Sep  5 21:53:42 localhost /weewxd: ambientweatherapi driver had an error sending data to weewx.
Sep  5 21:53:42 localhost journal: weewx[9788] ERROR root: ambientweatherapi driver had an error sending data to weewx.
Sep  5 21:53:42 localhost /weewxd: Error caught was: Previous error occured, skipping packet build.
Sep  5 21:53:42 localhost journal: weewx[9788] ERROR root: Error caught was: Previous error occured, skipping packet build.

**Comment by themoosman** [comment]
I don't see any of the `DEBUG` messages from the driver.

**Comment by pipporobby** [comment]
It's anything else I can try?

**Comment by themoosman** [comment]
Set this to `1` https://github.com/weewx/weewx/blob/master/weewx.conf#L11

**Comment by pipporobby** [comment]
I did it , what is the log name generate?

**Comment by themoosman** [comment]
`journalctl -r -u weewx`

**Comment by pipporobby** [comment]
I see some errors here:

Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG weewx.reportengine: Report 'RSYNC' not enabled. Skipping.
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG weewx.reportengine: Report 'FTP' not enabled. Skipping.
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG weewx.reportengine: No generators specified for report 'Belchertown'
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG weewx.reportengine: Cannot read skin configuration file /etc/weewx/skins/Belch
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG weewx.reportengine: Running report 'Belchertown'
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG weewx.reportengine: Report 'StandardReport' not enabled. Skipping.
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG weewx.reportengine: Report 'MobileReport' not enabled. Skipping.
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG weewx.reportengine: Report 'SmartphoneReport' not enabled. Skipping.
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG weewx.reportengine: No generators specified for report 'SeasonsReport'
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG root: sleeping an extra 3 seconds to not hit API throttle limit.
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG weewx.reportengine: Cannot read skin configuration file /etc/weewx/skins/Seaso
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG root: starting getLoopPackets
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG weewx.reportengine: Running report 'SeasonsReport'
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG root: calling: genLoopPackets
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] DEBUG weewx.reportengine: Running reports for latest time in the database.
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] INFO weewx.manager: Added record 2020-09-05 20:02:00 PDT (1599361320) to daily summa
Sep 05 20:05:23 localhost.localdomain weewxd[13551]: weewx[13551] INFO weewx.manager: Added record 2020-09-05 20:02:00 PDT (1599361320) to databa

**Comment by pipporobby** [comment]
I think error in skin, my mistake

**Comment by themoosman** [comment]
Okay, if the problem is fixed please close this issue.

**Comment by pipporobby** [comment]
Thank you very much!!
