### ISSUE TITLE
Battery Low message

### ISSUE THREAD

**Issue by staze** [themoosman/weewx-ambientweatherapi-json#17]
Not sure if this is the ambientweather api extension, or something in weewx, but it somewhere WeeWx is pulling that the battery level is "low" for my station, but I don't see that data anywhere in Ambient Weather. 

See here: https://www.staze.org/weewx/ on left hand side. 

I'm pushing to AW via a Meteobridge Nano SD (Ambientweather version) from my Davis Vantage Vue. 

Is there any way to disable this?

**Comment by themoosman** [comment]
You need to open an issue with WeeWx as they provide the driver for your device.  https://github.com/weewx/weewx/blob/master/bin/weewx/drivers/vantage.py

**Comment by staze** [comment]
Hi there,

Happy to do so, but want to make sure I understand. 

I configured weewx to use this driver. So, I'm wanting to make sure I understand how the Davis Vantage driver is involved... is the ambientweather driver figuring out I have a Vantage and bringing in something from the Vantage driver?

From my weewx.conf:

`station_type = ambientweatherapi`

<snip>

```
[ambientweatherapi]
    # This section for the AmbientWeatheAPI driver for weewx
    
    # The time (in seconds) between LOOP packets and getting API data
    # The ObserverIP only pushes data every 60 seconds.
    loop_interval = 60
    
    #API Log level
    log_level = ERROR
    
    #Log file location
    log_file = ""
    
    #URL to the Ambient Weather API
    api_url = https://api.ambientweather.net/v1
    
    #Ambient Weather API App Key
    api_app_key = <redacted>
    
    #Ambient Weather API Key
    api_key = <redacted>
    
    # Name of Hardware device.
    hardware = "Vantage Vue, MB Nano SD"
    
    # The driver to use:
    driver = user.ambientweatherapi
```

**Comment by staze** [comment]
fwiw, I do see "All Batteries are OK" in the AmbientWeather dashboard now... so I guess I'm now even more confused why it's showing battery low.

**Comment by themoosman** [comment]
All this driver does is pull the data from AW and supplies it to WeeWx.  AFAIK, AW only reports battery status as binary.  Since I don't have a Vantage, I don't know how it reports battery data.

**Comment by staze** [comment]
That's fair. I found the battery logic in the driver, and it seems relatively straight forward. 

Is there an easy way to look at what AW is providing in some verbose way?

**Comment by themoosman** [comment]
You can use the `app_key` and `key` and make the API calls yourself.  This will help:  https://ambientweather.docs.apiary.io/#reference/0/device-data/query-device-data

On a side note did you say Meteobridge?  If so, it looks like they flip 1 and 0.  https://github.com/ambient-weather/api-docs/wiki/Device-Data-Specs Why `0` would be Okay is beyond me.

**Comment by staze** [comment]
https://ambientweather.docs.apiary.io/#introduction/other-resources

Worked. 

Looks like it's reporting battery as 0. 

      "battin": 0,
      "battout": 0,

Good info about the Meteobridge. Yes indeed, that is what I have.

**Comment by themoosman** [comment]
Can you open an issue for this directly and I'll fix it?  It will require an additional setting in the driver config.
