### ISSUE TITLE
Error when running 1st step

### ISSUE THREAD

**Issue by checked-wobbles-0p** [themoosman/weewx-ambientweatherapi-json#25]
Running: sudo -H pip3 install -r requirements.txt and getting the below error. I feel like I am missing something stupid!!

<img width="636" alt="Screen Shot 2022-05-29 at 4 00 08 PM" src="https://user-images.githubusercontent.com/99628102/170891265-b7de51f0-3814-4f0d-ac30-647291d427c8.png">

**Comment by themoosman** [comment]
You need to `cd` into the directory where the requirements.txt file exists.
