### ISSUE TITLE
ambientweatherapi error when using mqtt and mosquitto

### ISSUE THREAD

**Issue by mjm455** [themoosman/weewx-ambientweatherapi-json#38]
I installed the Belchertown skin and configured the conf file to use mqtt and mosquitto.  My reports are working and the skin goes get updated but I'm getting the following error on the webpage:

Failed connecting to the weather station. Please try again later! Last Updated 26 July 2024, 23:10:00

The reason I'm posting this error here is that running journalctl shows the following error:

Jul 26 23:16:30 raspberrypi weewxd[1141]: ERROR user.ambientweatherapi: AmbientAPI get_devices() returned empty dict
Jul 26 23:16:30 raspberrypi weewxd.py[1141]: ambientweatherapi driver encountered an error.
Jul 26 23:16:30 raspberrypi weewxd[1141]: ERROR user.ambientweatherapi: ambientweatherapi driver encountered an error.
Jul 26 23:16:30 raspberrypi weewxd.py[1141]: Error caught was: AmbientAPI get_devices() returned empty dict
Jul 26 23:16:30 raspberrypi weewxd[1141]: ERROR user.ambientweatherapi: Error caught was: AmbientAPI get_devices() returned empty dict
Jul 26 23:16:30 raspberrypi weewxd.py[1141]: ambientweatherapi driver had an error sending data to weewx.
Jul 26 23:16:30 raspberrypi weewxd[1141]: ERROR user.ambientweatherapi: ambientweatherapi driver had an error sending data to weewx.
Jul 26 23:16:30 raspberrypi weewxd.py[1141]: Error caught was: Previous error occured, skipping packet build.
Jul 26 23:16:30 raspberrypi weewxd[1141]: ERROR user.ambientweatherapi: Error caught was: Previous error occured, skipping packet build.

I posted this error on the Google Groups for weewx and was receiving some help but I haven't seen a reply in about a week.  Here is that thread: https://groups.google.com/g/weewx-user/c/euaqDGRGXsQ

**Comment by themoosman** [comment]
This means no data is returned from the AmbientAPI.  It will happen from time to time.  If no data is returned from the API, the driver will try again on the next interval.  You can't expect 4 9's uptime because Ambient does not charge for API usage.

For more details, set `aw_debug` to '1' to drill into why.  https://github.com/themoosman/weewx-ambientweatherapi-json?tab=readme-ov-file#weewxconf-overview

These errors have nothing to do with MQTT.

**Comment by mjm455** [comment]
What do you mean "4 9s"?  

So you're saying that even though it is showing an error, it is not the reason why MQTT is not posting live to my weather station page?  And that these errors are acceptable?

**Comment by themoosman** [comment]
Those errors are related to pulling your data from Ambient and have nothing to do with the UI errors you see. WeeWx calls the Ambient API every 30-600 seconds, depending on how you set it up. Sometimes, it does not return data; those are the errors you occasionally see. If the error occurs, it will try again on the next loop cycle. We're dealing with hobbisty weather data, not medical research.  

Your MQTT issue screams of a firewall block.  Chrome Developer Tools should help you troubleshoot the problem.

**Comment by mjm455** [comment]
Thanks for your help.  I turned off my pihole, added listener 1883 to mosquitto.conf, and verified with netstat that the 1883 port is open.  But I'm still getting the error that it failed to connect to weather station.  Good news is that my local website for this is updating.

First gotta figure this out and then find a website that can host this page for me at no cost.  Not sure if that exists.
