### ISSUE TITLE
Empty Device list return

### ISSUE THREAD

**Issue by cyberralf83** [themoosman/weewx-ambientweatherapi-json#4]
Thanks again for your quick fix of the last issue. For the hardware field I have tried both the MAC address and the name of the device listed on the ambient weather portal. Here is the log, please advise. 

May 25 11:15:47 PiBridge weewx[2803] INFO weewx.restx: AWEKAS: Posting not enabled.
May 25 11:15:47 PiBridge weewx[2803] INFO __main__: Starting up weewx version 4.0.0
May 25 11:15:47 PiBridge weewx[2803] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
May 25 11:15:47 PiBridge weewx[2803] INFO weewx.manager: Starting backfill of daily summaries
May 25 11:15:47 PiBridge weewx[2803] INFO weewx.engine: Starting main packet loop.
May 25 11:15:50 PiBridge weewx[2803] ERROR root: AmbientAPI get_devices() returned empty dict
May 25 11:15:50 PiBridge /weewxd: ambientweatherapi driver encountered an error.
May 25 11:15:50 PiBridge weewx[2803] ERROR root: ambientweatherapi driver encountered an error.
May 25 11:15:50 PiBridge /weewxd: Error caught was: AmbientAPI get_devices() returned empty dict

**Comment by themoosman** [comment]
Did you add/update the API keys  https://github.com/themoosman/weewx-ambientweatherapi-json/blob/master/weewx.conf#L23-L26 in the weewx.conf file?

**Comment by cyberralf83** [comment]
updated but I get the same error, can i email you the config file?

**Comment by themoosman** [comment]
Does `curl --include 'https://api.ambientweather.net/v1/devices?applicationKey=[APP_KEY]&apiKey=[API_KEY]'` return anything?

**Comment by cyberralf83** [comment]
[{"macAddress":"CC:50:REDACTED","lastData":{"dateutc":1590427560000,"tempinf":77.4,"humidityin":48,"baromrelin":30.476,"baromabsin":30.177,"tempf":73.2,"humidity":62,"winddir":323,"windspeedmph":1.8,"windgustmph":2.2,"maxdailygust":8.1,"hourlyrainin":0,"eventrainin":0,"dailyrainin":0,"weeklyrainin":0,"monthlyrainin":3.48,"totalrainin":42.461,"solarradiation":577.79,"uv":5,"feelsLike":73.13,"dewPoint":59.39,"feelsLikein":77.1,"dewPointin":56.2,"lastRain":"2020-05-23T08:34:00.000Z","tz":"America/New_York","date":"2020-05-25T17:26:00.000Z"},"info":{"name":"Truxton Row Station","location":"Home","coords":{"coords":{"lat":REDACTED,"lon":-REDACTED},"address":"REDACTED Washington, DC 20001, USA","location":"Washington","elevation":33.527998927107085,"geo":{"type":"Point","coordinates":[-REDACTED]}}}}]curl: (6) Could not resolve host: Your
curl: (6) Could not resolve host: snippets

**Comment by themoosman** [comment]
Okay, so the keys work.  I'd rather not put my email here.  Can you post the sanitized config somewhere?  gist, pastebin, here?

**Comment by cyberralf83** [comment]
cryptobin.co/b0b6e6v8 
pw: weewx
It will self destroy after one view

**Comment by themoosman** [comment]
Okay, I noticed one minor thing.  The `api_app_key` value has a trailing space.

**Comment by cyberralf83** [comment]
fixed, but still getting: 

May 25 14:15:25 PiBridge weewx[6173] INFO weewx.engine: Starting main packet loop.
May 25 14:15:28 PiBridge weewx[6173] ERROR root: AmbientAPI get_devices() returned empty dict
May 25 14:15:28 PiBridge /weewxd: ambientweatherapi driver encountered an error.
May 25 14:15:28 PiBridge weewx[6173] ERROR root: ambientweatherapi driver encountered an error.

**Comment by themoosman** [comment]
`AmbientAPI get_devices() returned empty dict` means the call to the API failed or returned an empty json string.
In the `weewx.conf` file, can you remove the single quotes from `api_app_key` and `api_key`.  Also how are you starting weewx?

**Comment by cyberralf83** [comment]
Removed the quotes but no luck. 
My setup: 
Installed Weewx on Raspberry Pi 4 with deb package manager. 
Starting with sudo /etc/init.d/weewx start
Config file in /etc/weewx/weewx.conf
Copied ambientweatherapi.py and humidity.py to /usr/share/weewx/user/

**Comment by themoosman** [comment]
I don't have a Pi4, but let me fire up a Debian instance and test it out.

**Comment by themoosman** [comment]
So, I just set up a fresh Debian Buster instance and got it to work without any issues.  In the weewx.conf file can you set `debug = 1` (it's at the top of the config) and restart weewx ('sudo systemctl restart weewx')  Then tail /var/log/syslog, you should see the connection attempt like:
```
May 26 02:39:40 deb-buster weewx[10633] DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): api.ambientweather.net:443
May 26 02:39:40 deb-buster weewx[10633] DEBUG urllib3.connectionpool: https://api.ambientweather.net:443 "GET /v1/devices?applicationKey=xxxx&apiKey=xxxx HTTP/1.1" 200 721
```

**Comment by cyberralf83** [comment]
So I feel stupid but in your config the fields are reversed and don't match the comments
#Ambient Weather API Key
    api_**app**_key = ''
 #Ambient Weather API **App** Key
    api_key = ''

Now my problem is: 
May 26 00:31:15 PiBridge weewx[3764] DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): api.ambientweather.net:443
May 26 00:31:15 PiBridge weewx[3764] DEBUG urllib3.connectionpool: https://api.ambientweather.net:443 "GET /v1/devices?applicationKey=REDACTED&apiKey=REDACTED HTTP/1.1" 200 None
May 26 00:31:15 PiBridge weewx[3764] DEBUG root: Got weather devices
May 26 00:31:15 PiBridge weewx[3764] DEBUG root: Weather get_devices() payload not empty
May 26 00:31:15 PiBridge weewx[3764] DEBUG root: Got last report
May 26 00:31:15 PiBridge weewx[3764] DEBUG root: calling: convert_epoch_ms_to_sec
May 26 00:31:15 PiBridge weewx[3764] DEBUG root: calling: get_value
May 26 00:31:15 PiBridge weewx[3764] DEBUG root: calling: get_battery_status
May 26 00:31:15 PiBridge weewx[3764] DEBUG root: calling: get_value**...**

May 26 00:31:15 PiBridge /weewxd: ambientweatherapi driver encountered an error.
May 26 00:31:15 PiBridge weewx[3764] ERROR root: ambientweatherapi driver encountered an error.
May 26 00:31:15 PiBridge /weewxd: Error caught was: 'yearlyrainin'
May 26 00:31:15 PiBridge weewx[3764] ERROR root: Error caught was: 'yearlyrainin'
May 26 00:31:15 PiBridge weewx[3764] DEBUG root: ============Starting Packet Build============
May 26 00:31:15 PiBridge /weewxd: ambientweatherapi driver had an error sending data to weewx.
May 26 00:31:15 PiBridge weewx[3764] ERROR root: ambientweatherapi driver had an error sending data to weewx.
May 26 00:31:15 PiBridge /weewxd: Error caught was: Previous error occured, skipping packet build.

Oy!

**Comment by cyberralf83** [comment]
fixed by removing 	`yearlyrainin = data["yearlyrainin"]` from  ambientweatherapi.py

**Comment by themoosman** [comment]
I'm glad it's working and I'll fix that issue with the vars.  What weather station do you have?  I'm wondering why `yearlyrainin` isn't valid.

**Comment by cyberralf83** [comment]
I guess it would have just been easier to reply via email. Ambient Weather WS-2902B. I looked at the API response and yearlyrainin wasn’t in there. 🤷🏻‍♂️. I am so glad you made this plugin, I was definitely not going to go with the traffic intercepter.

**Comment by cyberralf83** [comment]
Also, you should see if they will add the API to the driver’s list here to help people find it: https://github.com/weewx/weewx/wiki <https://github.com/weewx/weewx/wiki>

**Comment by themoosman** [comment]
Please create an issue for the item above.
