### ISSUE TITLE
No module named ambient_api.ambientapi

### ISSUE THREAD

**Issue by cyberralf83** [themoosman/weewx-ambientweatherapi-json#5]
Hello, 
After running an update I am now getting the "No module named ambient_api.ambientapi" error. I have tried uninstalling and then re-installing the with "sudo -H pip3 install ambient_api" but without luck. Here is a log:

Jun 10 00:25:32 PiBridge weewx[8373]: Starting weewx weather system: weewx.
Jun 10 00:25:32 PiBridge systemd[1]: Started LSB: weewx weather system.
Jun 10 00:25:32 PiBridge weewx[8389] DEBUG __main__: Initializing engine
Jun 10 00:25:32 PiBridge weewx[8389] INFO weewx.engine: Loading station type ambientweatherapi (user.ambientweatherapi)
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__: Caught unrecoverable exception:
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__:     ****  No module named ambient_api.ambientapi
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__:     ****  Traceback (most recent call last):
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 148, in main
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 69, in __init__
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__:     ****      self.setupStation(config_dict)
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 92, in setupStation
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__:     ****      __import__(driver)
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__:     ****    File "/usr/share/weewx/user/ambientweatherapi.py", line 9, in <module>
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__:     ****      from ambient_api.ambientapi import AmbientAPI
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__:     ****  ImportError: No module named ambient_api.ambientapi
Jun 10 00:25:32 PiBridge weewx[8389] CRITICAL __main__:     ****  Exiting.
Jun 10 00:26:09 PiBridge weewxd: ambientweatherapi driver encountered an error.
Jun 10 00:26:09 PiBridge weewx[3729] ERROR root: ambientweatherapi driver encountered an error.
Jun 10 00:26:09 PiBridge weewxd: Error caught was: global name 'AmbientAPI' is not defined

**Comment by themoosman** [comment]
What happens if you run `sudo pip3 install ambient_api`?

**Comment by cyberralf83** [comment]
pi@PiBridge:~ $ sudo pip3 install ambient_api
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: ambient_api in /usr/local/lib/python3.7/dist-packages (1.5.5)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from ambient_api) (2.23.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from ambient_api) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->ambient_api) (2.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->ambient_api) (2020.4.5.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->ambient_api) (3.0.4)

**Comment by themoosman** [comment]
What changed from your previous config.  This is weird...  What version of weewx?

**Comment by themoosman** [comment]
@cyberralf83 Are you still seeing an issue?  If no, I'd like to close this out.

**Comment by cyberralf83** [comment]
I started on a fresh operating system and it worked. Thanks.
