### ISSUE TITLE
Missing API values cause error

### ISSUE THREAD

**Issue by uajqq** [themoosman/weewx-ambientweatherapi-json#6]
When a given value is not present in the data returned from the API call (for me, “yearlyrainin” and “pm25”), the driver throws an error and will not build the packet. Is there any way to have the driver continue and just not include data if it isn’t present?

**Comment by themoosman** [comment]
Yeah, I've got that on the TODO list.

**Comment by uajqq** [comment]
Thanks so much for making this driver, yours is the only one that actually makes these stations usable!

**Comment by themoosman** [comment]
I've got a couple of ideas on how I can solve the problem.  Now that you've opened the issue it will motivate me to sit my rear in the chair and implement the fix.
