### ISSUE TITLE
Absolute and relative pressure are reversed

### ISSUE THREAD

**Issue by uajqq** [themoosman/weewx-ambientweatherapi-json#7]
In the driver code, it looks like the value for “pressure” is being supplied by “baromrelin,” and “barometer” is supplied by “baromabsin.” The weewx docs specify this as the other way around: “pressure” should be “absolute” or “station” pressure, and “barometer” should be corrected sea-level pressure, which is represented by “baromrelin.”

**Comment by themoosman** [comment]
Resolved.
