### ISSUE TITLE
Rain reporting much higher than actual values

### ISSUE THREAD

**Issue by uajqq** [themoosman/weewx-ambientweatherapi-json#8]
My station using this software kept reporting daily rain in the hundreds of inches for even light showers. I finally figured out this is because the driver gives the “rain” value as “dailyrain,” when weewx expects the “rain” value to be the amount of rain since the last packet loop, not since the beginning of the day. Therefore, if I actually got 0.25 inches of rain in a day, the driver was instead reporting 0.25 inches every 1 minute for the entire day.

My (messy) fix was to add code so that the driver writes the dailyrain value to a text file. That way, on the next loop, the driver checks the previous dailyrain value, subtracts it from the new dailyrain value, and reports the interval rain. It then overwrites the dailyrain value in the file so the next loop can begin anew.

**Comment by themoosman** [comment]
Are you going to open a PR with that fix?

**Comment by uajqq** [comment]
I opened a pull request with my fix (and the fixes for the barometer issue)

**Comment by themoosman** [comment]
For reference:  http://weewx.com/docs/usersguide.htm#Data_is_archived_but_some_all_reports_do_not_run

**Comment by themoosman** [comment]
Fixed in #9 `
